# Generated by Django 4.1.2 on 2022-10-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год постройки')),
                ('area', models.CharField(max_length=500, verbose_name='Квартал')),
                ('residence_name', models.CharField(max_length=100, verbose_name='Название ЖК')),
                ('builder', models.CharField(max_length=50, verbose_name='Застрощик')),
            ],
            options={
                'verbose_name': 'Новостройка',
                'verbose_name_plural': 'Новостройки',
                'db_table': 'BuildingsBase',
            },
        ),
    ]
